baseURL: "https://yyq83.github.io/notion-hugo"
title: Blog template
theme: PaperMod

pagination:
  pagerSize: 5  # 替换 paginate

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - JSON

menu:
  main:
    - name: Categories
      url: categories/
      weight: 1
    - name: Tags
      url: tags/
      weight: 2
    - name: Search
      url: search/
      weight: 3
    - name: About
      url: about/
      weight: 4

params:
  env: production
  description: "Blog made from Notion with Hugo, hosted on GitHub Pages"
  keywords: [blog, hugo, notion, github]
  defaultTheme: auto
  disableThemeToggle: true
  disableSpecial1stPost: true
  ShowCodeCopyButtons: true
  ShowToc: true
  mainSections:
    - posts

  profileMode:
    enabled: false
    title: Blog template
    subtitle: "Blog made from Notion with Hugo and GitHub Pages"

  # 将 socialIcons 移动到 params 下
  socialIcons:
    - name: github
      url: "https://github.com/Malsius/blog-template"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
